name: Java CI with Gradle and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-dockerize:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build JAR with Gradle
      run: ./gradlew build

    - name: List generated JARs
      run: ls -lah build/libs

    - name: Copy and rename JAR for Docker
      run: |
        mkdir -p docker
        cp build/libs/*.jar docker/app.jar

    - name: Build Docker Image
      run: docker build -t java-app -f docker/Dockerfile docker

    - name: Tag Docker Image
      run: docker tag java-app njokadeclan/java-app:java-1.0

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: docker push njokadeclan/java-app:java-1.0
